"""Analytics thresholds and bucket definitions."""

TURN_ANGLE_THRESHOLD_DEGREES = 20.0
SHARP_TURN_ANGLE_THRESHOLD_DEGREES = 25.0

STEERING_INTENSITY_BUCKET_DEFINITIONS = (
    ("0-5°", 0, 5),
    ("5-10°", 5, 10),
    ("10-15°", 10, 15),
    ("15-20°", 15, 20),
    ("20-25°", 20, 25),
    ("25°+", 25, None),
)

STEERING_INTENSITY_BUCKET_COUNT = len(STEERING_INTENSITY_BUCKET_DEFINITIONS)

CORRELATION_THRESHOLD = 0.3
LOW_STEERING_VARIABILITY_THRESHOLD = 10.0
HIGH_STEERING_VARIABILITY_THRESHOLD = 20.0
LOW_SPEED_VARIABILITY_THRESHOLD = 10.0
REVERSE_INSIGHT_THRESHOLD = 0.1
